package de.bentrm.datacat.catalog.domain;

public enum CatalogRecordType {
    Activity,
    Actor,
    ActsUpon,
    AssignsCollections,
    AssignsMeasures,
    AssignsProperties,
    AssignsPropertyWithValues,
    AssignsUnits,
    AssignsValues,
    Associates,
    Bag,
    Classification,
    Collects,
    Composes,
    Documents,
    ExternalDocument,
    Groups,
    Measure,
    Nest,
    Property,
    Sequences,
    Specializes,
    Subject,
    Unit,
    Value,
}
