package de.bentrm.datacat.domain;

// TODO: Rename to CatalogItemType
public enum EntityType {
    XtdExternalDocument,
    XtdRoot,
    XtdObject,
    XtdActivity,
    XtdActor,
    XtdClassification,
    XtdMeasureWithUnit,
    XtdProperty,
    XtdSubject,
    XtdUnit,
    XtdValue,
    XtdCollection,
    XtdBag,
    XtdNest,
    XtdRelationship,
    XtdRelActsUpon,
    XtdRelAssignsCollections,
    XtdRelAssignsMeasures,
    XtdRelAssignsProperties,
    XtdRelAssignsPropertyWithValues,
    XtdRelAssignsUnit,
    XtdRelAssignsValues,
    XtdRelAssociates,
    XtdRelClassifies,
    XtdRelCollects,
    XtdRelComposes,
    XtdRelDocuments,
    XtdRelGroups,
    XtdRelSequences,
    XtdRelSpecializes
}
